apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: gcr.io/coodeshdictionary/laravel-app:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /var/www/html
          name: laravel-storage
      volumes:
      - name: laravel-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
  type: LoadBalancer
